name: Python env output

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MY_VAR: {{secrets.MY_VAR}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run the script to output env secret
        run: python env.py